### ISSUE TITLE
Jellyfin doesn't play next song in queue if app isn't directly open(background).

### ISSUE THREAD

**Issue by ghost** [jellyfin-archive/jellyfin-client-ios#11] opened 2020-08-04 01:23 UTC
**Directions**
1. Open up a Music library, go to "Songs", click three buttons on first song, click "Play all from here"
2. Click the shuffle and loop(infinite) buttons, and let a song finish.

**Expected result**
- Regardless of the app being open or not, once a song finishes, it will go on to the next.

**Actual Result**
- If the app is open(on screen), the next song will play after the first. If the app is not(playing in background), it will just stop after the first song, requiring the user to bring the app to the foreground and re-hit the play button.

**Comment by anthonylavado** [comment] 2020-08-17 19:07
Is this meant for the released version, which is [Jellyfin Expo](https://github.com/jellyfin/jellyfin-expo/)? If so, I can move the issue for you 🙂

**Comment by ghost** [comment] 2020-08-17 23:51
Yep, go ahead.
This applies to all three of the issues I posted

**Comment by anthonylavado** [comment] 2020-08-21 06:28
Duplicate of https://github.com/jellyfin/jellyfin-expo/issues/19

**Closed as completed by anthonylavado** 2020-08-21 06:28 UTC
